# --- Níveis
def nv1():
   print('-' * 80)
   print(' --- INFORMAÇÕES DO JOGADOR --- ')
   print('-=-=-= Nível 1 -=-=-=')
   print('🛡️・Classe: Aprendiz de Poções')
   print('🔑・Requisitos: Variáveis, tipos primitivos e operadores aritméticos.')
   print('🎓・Visual: Traje base de calouro: o moletom verde da UFRPE, mochila básica e notebook. Sem brilho mágico.')
   print('🔮・Poder atual: Visão de Memória (Habilidade de declarar e nomear variáveis corretamente).')
   print('-' * 80)
def nv2():
   print('-' * 80)
   print(' --- INFORMAÇÕES DO JOGADOR --- ')
   print('-=-=-= Nível 2 -=-=-=')
   print('🛡️・Classe: Guardião de Hogwarts')
   print('🔑・Requisitos: Estruturas condicionais (if/elif/else) e operadores relacionais.')
   print('🎓・Visual: Controle sobre o fluxo: uma aura mística azul-néon emana do notebook/tablet, simbolizando a decisão dos dados.')
   print('🔥・Poder atual: O Oráculo do IF-ELSE (A capacidade de direcionar o fluxo do jogo).')
   print('-' * 80)
def nv3():
   print('-' * 80)
   print(' --- INFORMAÇÕES DO JOGADOR --- ')
   print('-=-=-= Nível 3 -=-=-=')
   print('🛡️・Classe: Príncipe Mestiço')
   print('🔑・Requisitos: Laços de repetição (while, for), contadores, acumuladores e listas.')
   print('🎓・Visual: Domínio sobre o tempo e a repetição: empunha o 𝗖𝗮𝗷𝗮𝗱𝗼 𝗱𝗼 𝗟𝗼𝗼𝗽 𝗜𝗻𝗳𝗶𝗻𝗶𝘁𝗼 (símbolo Python). Hologramas de código em ciclos orbitam o cajado.')
   print('🔮・Poder atual: O Infinito Controlado (Domínio sobre o tempo e grandes volumes de dados).')
   print('-' * 80)
def nv4():
   print('-' * 80)
   print(' --- INFORMAÇÕES DO JOGADOR --- ')
   print('-=-=-= Nível 4 -=-=-=')
   print('🛡️・Classe: Dumbledore')
   print('🔑・Requisitos: Funções, parâmetros, retorno e modularização.')
   print('🎓・Visual: O ápice: veste a 𝗖𝗮𝗽𝗮 𝗔𝗰𝗮𝗱𝗲̂𝗺𝗶𝗰𝗮 𝗱𝗲 𝗚𝗿𝗮̃𝗼-𝗠𝗲𝘀𝘁𝗿𝗲, tecida com circuitos dourados brilhando com funções Python. Auradourada e Grimório das Funções.')
   print('🔮・Poder atual: Invocação Modular (Capacidade de chamar poderes complexos com uma única palavra).')
   print('-' * 80)
